name: Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up environment variables
      run: |
        echo "REACT_APP_GEMINI_API_KEY=${{ secrets.REACT_APP_GEMINI_API_KEY }}" >> $GITHUB_ENV
        echo "REACT_APP_GET_IMAGE_URL=${{ secrets.REACT_APP_GET_IMAGE_URL }}" >> $GITHUB_ENV
        echo "REACT_APP_GET_RECIPES_FROM_INGREDIENTS_URL=${{ secrets.REACT_APP_GET_RECIPES_FROM_INGREDIENTS_URL }}" >> $GITHUB_ENV
        echo "REACT_APP_GET_RECIPES_BY_NAME_URL=${{ secrets.REACT_APP_GET_RECIPES_BY_NAME_URL }}" >> $GITHUB_ENV
        echo "REACT_APP_GET_DETAILED_RECIPE_URL=${{ secrets.REACT_APP_GET_DETAILED_RECIPE_URL }}" >> $GITHUB_ENV
        echo "REACT_APP_GET_MEAL_PLAN_URL=${{ secrets.REACT_APP_GET_MEAL_PLAN_URL }}" >> $GITHUB_ENV
        
    - name: Test Functions
      run: |
        cd Code/frontend
        npm install
        npx jest --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./Code/frontend/coverage/coverage-final.json
        flags: unittests
        name: codecov-umbrella
